import type { ReleaseManagement } from "../types/cms";

export const fallbackReleaseData: ReleaseManagement = {
  settings: {
    mainHeading: "Download AgentDock",
    mainDescription: "Available for Windows, macOS, and Linux (Experimental).",
    latestVersion: "v0.1.1",
    githubReleasesUrl: "https://github.com/crossainthero-lab/AgentDock/releases",
    showLegacyReleases: true,
    announcement: "",
    updatedAt: null,
  },
  platforms: [
    {
      platformKey: "windows",
      displayName: "Windows",
      currentVersion: "v0.1.1",
      isAvailable: true,
      primaryDownloadUrl:
        "https://github.com/crossainthero-lab/AgentDock/releases/download/v0.1.1_windows/AgentDock.Setup.0.1.1.exe",
      primaryButtonLabel: "Installer",
      secondaryDownloadUrl:
        "https://github.com/crossainthero-lab/AgentDock/releases/download/v0.1.1_windows/AgentDock.0.1.1.exe",
      secondaryButtonLabel: "Portable executable",
      statusLabel: "Available",
      releaseNote: "Recommended Windows release with installer and portable executable options.",
      releaseDate: null,
      displayOrder: 10,
      isVisible: true,
      updatedAt: null,
    },
    {
      platformKey: "macos",
      displayName: "macOS",
      currentVersion: "v0.1.0",
      isAvailable: true,
      primaryDownloadUrl:
        "https://github.com/crossainthero-lab/AgentDock/releases/download/v0.1.0_macOS/AgentDock-0.1.0-arm64.dmg",
      primaryButtonLabel: "Apple Silicon DMG",
      secondaryDownloadUrl:
        "https://github.com/crossainthero-lab/AgentDock/releases/download/v0.1.0_macOS/AgentDock-0.1.0.dmg",
      secondaryButtonLabel: "Intel Mac DMG",
      statusLabel: "Available",
      releaseNote: "DMG packages are available for Apple Silicon and Intel Macs.",
      releaseDate: null,
      displayOrder: 20,
      isVisible: true,
      updatedAt: null,
    },
    {
      platformKey: "linux",
      displayName: "Linux",
      currentVersion: "",
      isAvailable: false,
      primaryDownloadUrl: "",
      primaryButtonLabel: "Download package",
      secondaryDownloadUrl: "",
      secondaryButtonLabel: "",
      statusLabel: "Experimental",
      releaseNote: "Linux builds are currently experimental. Please install from source below.",
      releaseDate: null,
      displayOrder: 30,
      isVisible: true,
      updatedAt: null,
    },
  ],
  legacyReleases: [
    {
      id: 1,
      version: "v0.1.0",
      platform: "Windows",
      title: "Windows Installer",
      url: "https://github.com/crossainthero-lab/AgentDock/releases/download/v0.1.0_windows/AgentDock.Setup.0.1.0.exe",
      buttonLabel: "Download",
      releaseNotesUrl: "https://github.com/crossainthero-lab/AgentDock/releases/tag/v0.1.0_windows",
      fileType: ".exe",
      arch: "x64",
      displayOrder: 10,
      isVisible: true,
    },
    {
      id: 2,
      version: "v0.1.0",
      platform: "Windows",
      title: "Windows Portable",
      url: "https://github.com/crossainthero-lab/AgentDock/releases/download/v0.1.0_windows/AgentDock.0.1.0.exe",
      buttonLabel: "Download",
      releaseNotesUrl: "https://github.com/crossainthero-lab/AgentDock/releases/tag/v0.1.0_windows",
      fileType: ".exe",
      arch: "x64",
      displayOrder: 20,
      isVisible: true,
    },
  ],
};
